### ISSUE TITLE
OK button not working for extension "Data Driven Parameters"

### ISSUE THREAD

**Issue by karthikvalluri85** [tableau/extension-data-driven-parameters#65] opened 2020-01-08 15:09 UTC
Hi,
I am using the extension "Data-Driven Parameters" https://extensiongallery.tableau.com/products/27 in Tableau 2019.4.1. I am using the  sample super store dataset where I have created a calculated field for Order date to get the years - YEAR(OrderDate) . I have then created a parameter called "Years Param" with Allowable values set to "All". Both calculated filed and Parameter is in string data type all this are done in sheet1. In my dashboard I use the extension and set the values for sheet, param and field, however the OK button doesn't work. ( also I have pulled the field that populates the param in my view) Not able to figure out what is the problem. I amusing IE and I tried using the earlier version of the extension- but still the same issue. 
Any help will be appreciated.. 

The intention behind using this extension is tomorrow if I put in dates for 2021 and 2022 I should see these appearing in my parameters.

![TExt_issue](https://user-images.githubusercontent.com/17356407/71988732-6e759f80-3256-11ea-9042-6970a1a39ed1.PNG)

**Comment by KeshiaRose** [comment] 2020-01-08 17:24
Hi @karthikvalluri85,

I've heard this issue a couple of times now and I can't seem to be able to reproduce it.  Would you be willing to hop on a Webex with me so I could take a look at your environment? I know the issue is with the settings that are being set when OK is clicked but not sure which one.

Take care,
Keshia

**Comment by karthikvalluri85** [comment] 2020-01-09 09:02
Thanks for the update Keshia. Sure, let me know what time today (9/1) you are available to talk(EST time) ?

**Comment by KeshiaRose** [comment] 2020-01-09 15:35
I'm free at 12, 1 or 4 PM EST. If one of those works for you, send me an email at krose@tableau.com and I can send you a meeting invite!

**Comment by karthikvalluri85** [comment] 2020-01-10 14:39
Sure, I will send out an email from my id for 1 EST.

**Comment by KeshiaRose** [comment] 2020-01-14 19:42
I believe I've found the bug and fixed the issue. I'm going to close this, please reopen if you're still seeing it.

**Closed by KeshiaRose** 2020-01-14 19:42 UTC
