### ISSUE TITLE
Not able to configure , not working

### ISSUE THREAD

**Issue by scaffarelli** [tableau/extension-data-driven-parameters#48] opened 2019-10-13 11:14 UTC
@KeshiaRose I'm trying to test the extension however seems that I'm not able to save the changes (screenshot attached) . I've tested in Tableau desktop 2018.3 , 2019.1 and 2019.3 , same issue

Can you please check if something changed?

<img width="1160" alt="extension" src="https://user-images.githubusercontent.com/30665842/66714745-10d5d200-ed91-11e9-9e8f-6e203e870835.png">

Thanks
Sebastian

**Comment by KeshiaRose** [comment] 2019-10-13 14:12
Hi @scaffarelli,

No changes have been made to the extension for almost a month.  I am unable to reproduce your issue but I see you are on a Mac and maybe that has something to do with it. Are you able to select the button and then once it is in focus press Enter? Also, can you try adding the extension to a workbook in web authoring and see if it works for you there? That would help narrow down the issue. 

Take care,
Keshia

**Comment by scaffarelli** [comment] 2019-10-14 23:40
Hi Keshia, I’ve tested in Windows too and I got the same issue. What was interesting is that I was able to get it working today but a after I close it and open it again I wasn’t able to re-configured or even create a new one, seems that stopped working. 

I’m able to select the OK button but nothing happened, the windows never close.

I don’t have a server to test this, I can provide you the workbook if you wish to open it on your side. Will this work for you?

Thanks
Sebastian

**Comment by KeshiaRose** [comment] 2019-10-22 22:26
Hi @scaffarelli,

Sorry for the delayed response I've been out of town for a while. Feel free to send your workbook but I'm not sure if I will be able to repro it. It will help rule out some things though.

Take care,
Keshia

**Comment by KeshiaRose** [comment] 2020-01-14 19:43
I believe I've found the bug and fixed the issue. I'm going to close this, please reopen if you're still seeing it.

**Closed by KeshiaRose** 2020-01-14 19:43 UTC
Labels: bug, waiting reply

**Comment by Mirek-sikora** [comment] 2020-01-23 12:21
I had the same situation, and I found a workaround I need to add a minimum of 2 parameters in the workbook then button 'OK' works.
